# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170619_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_info_detail',
            old_name='frame_num',
            new_name='played_times',
        ),
        migrations.RenameField(
            model_name='music_info_detail',
            old_name='play_time',
            new_name='popularity',
        ),
    ]
