# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20170619_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_info_detail',
            name='music_tags',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
