# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_music_info_detail_music_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_info_detail',
            name='Class_Num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
